### PR TITLE
Fixed mixed use of spaces and tabs.

### PR DESCRIPTION
**Pull request by jcs090218**
I saw mixed use to spaces and tabs which I think is bad and doesn't display the code with the correct indentation level. This PR fixed most of the this cases. And I saw some of the trailing lines which is quite annoying when reading through the code! Please consider this PR is the improvement of readability. 

**Commits (2):**

This code split into 2 commits, one is the fixed and the other one is the IDE files changes. I am not quite sure what these files does 😕 yet I commit it anyway by look through it very fast with some reasonable changes. Like proper name with the module naming, etc.

On my end, the code doesn't changed and run properly! Please check this patch! Thanks! 😄

### CODE REVIEW

**Comment by sstokic-tgm** [comment]
Before all, thanks!

But, before I decide to merge I would like to discuss it with you shortly.

The type of ident (talking only about the ident/spaces) is personal opinion and in the end how it gets on github it doesn't matter.
Since you can adjust inside the IDE the indent spaces etc.

Which in my case this is:
grafik

So if having a formatter setted up, as soon as you open the project, the code gets formatted in the IDE.

**Comment by jcs090218** [comment]
Cool, I didn't notice this feature!

The problem is every editor display tab differently, unless you prefer spaces? I am fine with either spaces or tabs and this depends on you! I prefer spaces just because it display consistently on every editor and even on GitHub! The major issue that this PR fixed are the mixed use of spaces and tabs, and this is generally does not prefer to have; just because every one has their own editing method.

And this way, the project will be more open source friendly, so the newcomer wouldn't need to adjust their editor by default. :)

Well, this is just my suggestion! You don't have to merge this but I will prefer it to!

**Comment by sstokic-tgm** [comment]
Oke I see and you have a point there.
Just one more question, the changes made to the "project" itself - in this case the idea file changes, what settings did you change? So I know it in the overview what impact it would cause :)

**Comment by jcs090218** [comment]
Yeah, I am also having the question and since I am the very beginner to Intelliji and Android Studio, I actually no idea of those changes, which mean I have no intention to these files yet by readying the changes I don't think it would matter to local changes; if it does then I guess we should ignore it? 😕 

BTW, I found this stackoverflow question [here](https://stackoverflow.com/questions/11968531/what-to-gitignore-from-the-idea-folder). I assumed that we should ignore the `workspace.xml`? If this is the case, the thing I change are `compiler.xml` and `vcs.xml` files which I don't think it harms. 😕 

Well, since you have the better experience with Intelliji, what do you think?

**Comment by sstokic-tgm** [comment]
I merged and fixed up the .gitignore

**Comment by jcs090218** [comment]
Great! You might to set up your editor with the same settings so we can have the same style. 👍 And I think this should be one of our style guide rule for this project! 😄

**Pull request merged**
